#spring:
#  security:
#    oauth2:
#      client:
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
#        registration:
#          kakao:
#            client-id: aa5aaf6346a4d796ac90b1a920a41168
#            client-secret: SndVIm1vWTcSRgkGMapMZSCUA9ilRi81
#            client-authentication-method: client_secret_post
#            #//카카오 디벨로퍼 사이트에서 설정한 redirect-uri 값
#            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
#            authorization-grant-type: authorization_code
#            client-name: kakao

spring:
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: aa5aaf6346a4d796ac90b1a920a41168
            client-secret: SndVIm1vWTcSRgkGMapMZSCUA9ilRi81
            client-authentication-method: client_secret_post
            #//카카오 디벨로퍼 사이트에서 설정한 redirect-uri 값
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
server:
  port: 8080